runtime: nodejs12

instance_class: F4

handlers:
- url: /
  static_files: public/index.html
  upload: public/index.html

- url: /(.*\.(ico|png|css|js))$
  static_files: public/\1
  upload: public/.*\.(ico|png|css|js)$

- url: /robots\.txt
  static_files: server/robots.txt
  upload: server/robots.txt

- url: /sitemap\.xml
  static_files: server/sitemap.xml
  upload: server/sitemap.xml

- url: /api/.*
  script: auto
  secure: always
  redirect_http_response_code: 301
