name: CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - README.md
      - .github/workflows/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - id: deploy
      uses: GoogleCloudPlatform/github-actions/appengine-deploy@master
      with:
        credentials: ${{ secrets.GCP_CREDENTIALS }}

    - id: test
      run: curl "${{ steps.deploy.outputs.url }}"
